# Generated by Django 3.2.13 on 2022-07-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0003_alter_member_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='members',
            field=models.ManyToManyField(related_name='channels', to='chatroom.Member'),
        ),
    ]
